In [1]:
import tensorflow as tf

tf.random.set_seed(1)
a_S = tf.random.normal([1, 4, 4, 3], mean=1, stddev=4)

In [2]:
a_S

<tf.Tensor: shape=(1, 4, 4, 3), dtype=float32, numpy=
array([[[[-3.404881  ,  7.183007  ,  2.534576  ],
         [-2.5186315 , -3.8986888 , -2.9244845 ],
         [ 1.3512313 ,  0.18695849, -1.2326248 ],
         [-1.8821762 , -1.5039697 , -1.8601038 ]],

        [[-0.39341784, -0.34587932,  1.730303  ],
         [ 5.434381  ,  6.1186347 ,  0.91409665],
         [-0.2787553 ,  2.493302  ,  2.0111642 ],
         [ 3.5750656 ,  9.585232  , -2.3005993 ]],

        [[-2.616547  ,  6.5795145 ,  5.8995004 ],
         [ 1.2345984 , -0.9685255 , -2.2799122 ],
         [ 0.25895953, -0.5711074 , -1.6340904 ],
         [-2.933355  ,  2.555351  , -3.1489792 ]],

        [[-5.2402277 ,  0.3683498 , -0.42677724],
         [ 0.19823885,  7.452428  ,  3.718691  ],
         [ 1.3253293 ,  6.3523054 ,  5.739221  ],
         [-0.41526246,  0.583993  , -2.0045857 ]]]], dtype=float32)>

In [3]:
a_1 = tf.reshape(a_S, [16, 3])
a_1 = tf.transpose(a_1)
a_1

<tf.Tensor: shape=(3, 16), dtype=float32, numpy=
array([[-3.404881  , -2.5186315 ,  1.3512313 , -1.8821762 , -0.39341784,
         5.434381  , -0.2787553 ,  3.5750656 , -2.616547  ,  1.2345984 ,
         0.25895953, -2.933355  , -5.2402277 ,  0.19823885,  1.3253293 ,
        -0.41526246],
       [ 7.183007  , -3.8986888 ,  0.18695849, -1.5039697 , -0.34587932,
         6.1186347 ,  2.493302  ,  9.585232  ,  6.5795145 , -0.9685255 ,
        -0.5711074 ,  2.555351  ,  0.3683498 ,  7.452428  ,  6.3523054 ,
         0.583993  ],
       [ 2.534576  , -2.9244845 , -1.2326248 , -1.8601038 ,  1.730303  ,
         0.91409665,  2.0111642 , -2.3005993 ,  5.8995004 , -2.2799122 ,
        -1.6340904 , -3.1489792 , -0.42677724,  3.718691  ,  5.739221  ,
        -2.0045857 ]], dtype=float32)>

In [4]:
a2=tf.reshape(a_S, [3, 16])
a2

<tf.Tensor: shape=(3, 16), dtype=float32, numpy=
array([[-3.404881  ,  7.183007  ,  2.534576  , -2.5186315 , -3.8986888 ,
        -2.9244845 ,  1.3512313 ,  0.18695849, -1.2326248 , -1.8821762 ,
        -1.5039697 , -1.8601038 , -0.39341784, -0.34587932,  1.730303  ,
         5.434381  ],
       [ 6.1186347 ,  0.91409665, -0.2787553 ,  2.493302  ,  2.0111642 ,
         3.5750656 ,  9.585232  , -2.3005993 , -2.616547  ,  6.5795145 ,
         5.8995004 ,  1.2345984 , -0.9685255 , -2.2799122 ,  0.25895953,
        -0.5711074 ],
       [-1.6340904 , -2.933355  ,  2.555351  , -3.1489792 , -5.2402277 ,
         0.3683498 , -0.42677724,  0.19823885,  7.452428  ,  3.718691  ,
         1.3253293 ,  6.3523054 ,  5.739221  , -0.41526246,  0.583993  ,
        -2.0045857 ]], dtype=float32)>